<?php

declare(strict_types=1);

namespace Cose\Tests\Key;

use function base64_decode;
use function bin2hex;
use Cose\Algorithm\Signature\ECDSA\ES256;
use Cose\Key\Ec2Key;
use Cose\Key\Key;
use Cose\Key\PublicKeyLoader;
use Cose\Tests\RaisesNoPhpError;
use function hex2bin;
use function in_array;
use InvalidArgumentException;
use function openssl_get_curve_names;
use const OPENSSL_KEYTYPE_EC;
use function openssl_pkey_get_details;
use function openssl_pkey_new;
use function ord;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use function preg_replace;
use function random_bytes;
use SpomkyLabs\Pki\ASN1\Type\Primitive\BitString;
use SpomkyLabs\Pki\CryptoTypes\Asymmetric\PublicKeyInfo;
use function sprintf;
use function str_pad;
use const STR_PAD_LEFT;
use function str_repeat;
use function strlen;

/**
 * The compressed point form of an EC2 key: "y" as the sign bit of RFC 9053, section 7.1.1, decompressed on load.
 *
 * @see \Cose\Key\Ec2Key
 */
final class Ec2KeyCompressedPointTest extends TestCase
{
    use RaisesNoPhpError;

    /**
     * For every curve, a key generated by OpenSSL and loaded from its x-coordinate and the parity of its y is the
     * key OpenSSL generated: y() is the coordinate OpenSSL computed, the DER is the same, and getData() still holds
     * the boolean.
     */
    #[Test]
    #[DataProvider('getCurves')]
    public function aCompressedPointIsDecompressed(int $curve, string $opensslName, int $length): void
    {
        // Given
        [$x, $y] = self::generate($opensslName, $length);
        $signBit = (ord($y[$length - 1]) & 1) === 1;
        $uncompressed = Ec2Key::create([
            Key::TYPE => Key::TYPE_EC2,
            Ec2Key::DATA_CURVE => $curve,
            Ec2Key::DATA_X => $x,
            Ec2Key::DATA_Y => $y,
        ]);

        // When
        $compressed = self::withoutPhpErrors(static fn (): Ec2Key => Ec2Key::create([
            Key::TYPE => Key::TYPE_EC2,
            Ec2Key::DATA_CURVE => $curve,
            Ec2Key::DATA_X => $x,
            Ec2Key::DATA_Y => $signBit,
        ]));

        // Then
        static::assertSame(bin2hex($y), bin2hex($compressed->y()));
        static::assertSame($length, strlen($compressed->y()));
        static::assertSame($uncompressed->getUncompressedCoordinates(), $compressed->getUncompressedCoordinates());
        static::assertSame($uncompressed->asPEM(), $compressed->asPEM());
        static::assertSame($signBit, $compressed->get(Ec2Key::DATA_Y));
        static::assertSame($signBit, $compressed->toPublic()->get(Ec2Key::DATA_Y));
        static::assertFalse($compressed->isPrivate());
    }

    /**
     * The other root: the same x with the opposite sign bit is the point p - y, which is on the curve too and whose
     * y differs from the generated one in every byte but its parity.
     */
    #[Test]
    #[DataProvider('getCurves')]
    public function theOppositeSignBitYieldsTheOtherRoot(int $curve, string $opensslName, int $length): void
    {
        // Given
        [$x, $y] = self::generate($opensslName, $length);
        $signBit = (ord($y[$length - 1]) & 1) === 1;

        // When
        $other = Ec2Key::create([
            Key::TYPE => Key::TYPE_EC2,
            Ec2Key::DATA_CURVE => $curve,
            Ec2Key::DATA_X => $x,
            Ec2Key::DATA_Y => ! $signBit,
        ]);

        // Then
        static::assertNotSame(bin2hex($y), bin2hex($other->y()));
        static::assertSame($length, strlen($other->y()));
        static::assertSame(! $signBit, (ord($other->y()[$length - 1]) & 1) === 1);
    }

    /**
     * A compressed key on a named curve is decompressed too, with the curve resolved the same way.
     */
    #[Test]
    public function aCompressedKeyMayNameItsCurve(): void
    {
        // Given
        [$x, $y] = self::generate('prime256v1', 32);

        // When
        $key = Ec2Key::create([
            Key::TYPE => Key::TYPE_NAME_EC2_IANA,
            Ec2Key::DATA_CURVE => Ec2Key::CURVE_NAME_P256,
            Ec2Key::DATA_X => $x,
            Ec2Key::DATA_Y => (ord($y[31]) & 1) === 1,
        ]);

        // Then
        static::assertSame(bin2hex($y), bin2hex($key->y()));
    }

    /**
     * A private key may carry its public point compressed; it signs, and the decompressed public half verifies.
     */
    #[Test]
    public function aCompressedPrivateKeySignsAndItsPublicHalfVerifies(): void
    {
        // Given
        $generated = openssl_pkey_new([
            'private_key_type' => OPENSSL_KEYTYPE_EC,
            'curve_name' => 'prime256v1',
        ]);
        static::assertNotFalse($generated);
        $details = openssl_pkey_get_details($generated);
        static::assertIsArray($details);
        $pad = static fn (string $value): string => str_pad($value, 32, "\0", STR_PAD_LEFT);
        $private = Ec2Key::create([
            Key::TYPE => Key::TYPE_EC2,
            Ec2Key::DATA_CURVE => Ec2Key::CURVE_P256,
            Ec2Key::DATA_X => $pad($details['ec']['x']),
            Ec2Key::DATA_Y => (ord($pad($details['ec']['y'])[31]) & 1) === 1,
            Ec2Key::DATA_D => $pad($details['ec']['d']),
        ]);
        $algorithm = ES256::create();

        // When
        $signature = $algorithm->sign('data', $private);

        // Then
        static::assertTrue($private->isPrivate());
        static::assertTrue($algorithm->verify('data', $private->toPublic(), $signature));
        static::assertFalse($algorithm->verify('other data', $private->toPublic(), $signature));
    }

    /**
     * An x-coordinate that lies on no point of the curve: x^3 + a*x + b is not a square modulo p, so no y exists and
     * the key is refused on load, with either sign bit. The values are the smallest such x of each curve.
     */
    #[Test]
    #[DataProvider('getOffCurveCoordinates')]
    public function anXThatIsOnNoPointOfTheCurveIsRejected(int $curve, int $length, int $x, bool $signBit): void
    {
        // Then
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('Invalid EC2 key. The compressed point is not on the curve');

        // When
        self::withoutPhpErrors(static fn (): Ec2Key => Ec2Key::create([
            Key::TYPE => Key::TYPE_EC2,
            Ec2Key::DATA_CURVE => $curve,
            Ec2Key::DATA_X => str_pad((string) hex2bin(sprintf('%02x', $x)), $length, "\0", STR_PAD_LEFT),
            Ec2Key::DATA_Y => $signBit,
        ]));
    }

    /**
     * @return iterable<string, array{int, int, int, bool}>
     */
    public static function getOffCurveCoordinates(): iterable
    {
        foreach ([
            'P-256' => [Ec2Key::CURVE_P256, 32, 1],
            'P-384' => [Ec2Key::CURVE_P384, 48, 1],
            'P-521' => [Ec2Key::CURVE_P521, 66, 3],
            'secp256k1' => [Ec2Key::CURVE_P256K, 32, 0],
            'brainpoolP256r1' => [Ec2Key::CURVE_BP256, 32, 0],
            'brainpoolP320r1' => [Ec2Key::CURVE_BP320, 40, 0],
            'brainpoolP384r1' => [Ec2Key::CURVE_BP384, 48, 0],
            'brainpoolP512r1' => [Ec2Key::CURVE_BP512, 64, 0],
        ] as $name => [$curve, $length, $x]) {
            yield $name . ', sign bit false' => [$curve, $length, $x, false];
            yield $name . ', sign bit true' => [$curve, $length, $x, true];
        }
    }

    /**
     * An x that is not smaller than the field prime is not a field element (SEC 1, section 2.3.4, step 2.2): a key
     * carrying one - the prime of P-256 itself here, or anything above it - is refused rather than reduced.
     */
    #[Test]
    public function anXOutsideTheFieldIsRejected(): void
    {
        // Then
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('Invalid EC2 key. The x coordinate is not a field element of the curve');

        // When
        Ec2Key::create([
            Key::TYPE => Key::TYPE_EC2,
            Ec2Key::DATA_CURVE => Ec2Key::CURVE_P256,
            Ec2Key::DATA_X => hex2bin('ffffffff00000001000000000000000000000000ffffffffffffffffffffffff'),
            Ec2Key::DATA_Y => true,
        ]);
    }

    /**
     * The sign bit does not relax the checks on x.
     */
    #[Test]
    public function aCompressedKeyWithAnXOfTheWrongLengthIsRejected(): void
    {
        // Then
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('Invalid length for x coordinate');

        // When
        Ec2Key::create([
            Key::TYPE => Key::TYPE_EC2,
            Ec2Key::DATA_CURVE => Ec2Key::CURVE_P256,
            Ec2Key::DATA_X => random_bytes(31),
            Ec2Key::DATA_Y => true,
        ]);
    }

    /**
     * Table 19 types "y" as "bstr / bool": anything else is still refused, an integer 1 is not "true".
     */
    #[Test]
    #[DataProvider('getInvalidYTypes')]
    public function aYThatIsNeitherAByteStringNorABooleanIsRejected(mixed $y): void
    {
        // Then
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('Invalid type for y coordinate');

        // When
        self::withoutPhpErrors(static fn (): Ec2Key => Ec2Key::create([
            Key::TYPE => Key::TYPE_EC2,
            Ec2Key::DATA_CURVE => Ec2Key::CURVE_P256,
            Ec2Key::DATA_X => random_bytes(32),
            Ec2Key::DATA_Y => $y,
        ]));
    }

    /**
     * @return iterable<string, array{mixed}>
     */
    public static function getInvalidYTypes(): iterable
    {
        yield 'the integer 1' => [1];
        yield 'the integer 0' => [0];
        yield 'a float' => [1.0];
        yield 'an array' => [[true]];
    }

    /**
     * RFC 5480, section 2.2 lets a SubjectPublicKeyInfo carry the point in the compressed form of SEC 1, section
     * 2.3.3 (0x02 or 0x03 followed by x). The loader now reads it, and the key it produces carries the uncompressed
     * point - the form RFC 9679 computes a thumbprint over.
     */
    #[Test]
    #[DataProvider('getCurves')]
    public function aCompressedSubjectPublicKeyInfoIsLoaded(int $curve, string $opensslName, int $length): void
    {
        // Given
        [$x, $y, $subjectPublicKeyInfo] = self::generate($opensslName, $length);
        $compressedPoint = ((ord($y[$length - 1]) & 1) === 1 ? "\x03" : "\x02") . $x;
        static::assertStringContainsString("\x04" . $x . $y, $subjectPublicKeyInfo);
        $compressedSpki = self::withPoint($subjectPublicKeyInfo, $compressedPoint);

        // When
        $key = PublicKeyLoader::fromSubjectPublicKeyInfo($compressedSpki);

        // Then
        static::assertSame($curve, $key->curveId());
        static::assertSame(bin2hex($x), bin2hex($key->x()));
        static::assertSame(bin2hex($y), bin2hex($key->y()));
        static::assertSame($y, $key->get(Ec2Key::DATA_Y), 'The loaded key carries the coordinate, not the sign bit');
        static::assertSame(PublicKeyLoader::fromSubjectPublicKeyInfo($subjectPublicKeyInfo)->getData(), $key->getData());
    }

    /**
     * A SubjectPublicKeyInfo whose compressed point names no point of the curve is refused, as the key form is.
     */
    #[Test]
    public function aCompressedSubjectPublicKeyInfoOffTheCurveIsRejected(): void
    {
        // Given
        [$x, $y, $subjectPublicKeyInfo] = self::generate('prime256v1', 32);
        $compressedSpki = self::withPoint($subjectPublicKeyInfo, "\x02" . str_repeat("\0", 31) . "\x01");

        // Then
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('Invalid EC2 key. The compressed point is not on the curve');

        // When
        PublicKeyLoader::fromSubjectPublicKeyInfo($compressedSpki);
    }

    /**
     * The point formats other than 0x02, 0x03 and 0x04 - the hybrid 0x06 / 0x07 of X9.62, or garbage - are still
     * refused by name.
     */
    #[Test]
    public function aHybridPointIsStillRejected(): void
    {
        // Given
        [$x, $y, $subjectPublicKeyInfo] = self::generate('prime256v1', 32);
        $hybridSpki = self::withPoint($subjectPublicKeyInfo, ((ord($y[31]) & 1) === 1 ? "\x07" : "\x06") . $x . $y);

        // Then
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('only the uncompressed and compressed point formats are supported');

        // When
        PublicKeyLoader::fromSubjectPublicKeyInfo($hybridSpki);
    }

    /**
     * @return iterable<string, array{int, string, int}>
     */
    public static function getCurves(): iterable
    {
        yield 'P-256' => [Ec2Key::CURVE_P256, 'prime256v1', 32];
        yield 'P-384' => [Ec2Key::CURVE_P384, 'secp384r1', 48];
        yield 'P-521' => [Ec2Key::CURVE_P521, 'secp521r1', 66];
        yield 'secp256k1' => [Ec2Key::CURVE_P256K, 'secp256k1', 32];
        yield 'brainpoolP256r1' => [Ec2Key::CURVE_BP256, 'brainpoolP256r1', 32];
        yield 'brainpoolP320r1' => [Ec2Key::CURVE_BP320, 'brainpoolP320r1', 40];
        yield 'brainpoolP384r1' => [Ec2Key::CURVE_BP384, 'brainpoolP384r1', 48];
        yield 'brainpoolP512r1' => [Ec2Key::CURVE_BP512, 'brainpoolP512r1', 64];
    }

    /**
     * A fresh key of OpenSSL on the curve: its coordinates padded to the length of the curve, and the DER of its
     * SubjectPublicKeyInfo. Skips the test when this OpenSSL build was made without the curve.
     *
     * @return array{string, string, string}
     */
    private static function generate(string $opensslName, int $length): array
    {
        $curves = openssl_get_curve_names();
        if ($curves === false || ! in_array($opensslName, $curves, true)) {
            static::markTestSkipped(sprintf('This OpenSSL build does not provide the %s curve', $opensslName));
        }
        $generated = openssl_pkey_new([
            'private_key_type' => OPENSSL_KEYTYPE_EC,
            'curve_name' => $opensslName,
        ]);
        static::assertNotFalse($generated);
        $details = openssl_pkey_get_details($generated);
        static::assertIsArray($details);
        $pad = static fn (string $value): string => str_pad($value, $length, "\0", STR_PAD_LEFT);

        return [$pad($details['ec']['x']), $pad($details['ec']['y']), self::pemToDer($details['key'])];
    }

    /**
     * The same SubjectPublicKeyInfo with another point in its BIT STRING.
     */
    private static function withPoint(string $spki, string $point): string
    {
        $parsed = PublicKeyInfo::fromDER($spki);

        return PublicKeyInfo::create($parsed->algorithmIdentifier(), BitString::create($point))->toDER();
    }

    private static function pemToDer(string $pem): string
    {
        return (string) base64_decode((string) preg_replace('#-----[^-]+-----|\s#', '', $pem), true);
    }
}
